### ISSUE TITLE
customElements is not defined

### ISSUE THREAD

**Issue by yalcinozer** [GoogleChromeLabs/pinch-zoom#15]
Hey guys I tested it and works great on my phone. But on some other phones and also some emulators I tested on, I got "customElements is not defined" error. My phone is Andorid v5.0, strangely emulator works on v7.1.1

Thanks.

**Comment by madosa-dev** [comment]
How did you fixed it ?

**Comment by yalcinozer** [comment]
> How did you fixed it ?

I couldn't. But its not library's fault, the problem is customelements is not a very well supported by browsers so I had used another plugin. Its not good as pinch-zoom but worths a try.
sarriaroman/photoviewer
